// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1635850406);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1635850166);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1635850286);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1635850196);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1635850526);
user_pref("browser.cache.disk.amount_written", 923);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("calendar.list.sortOrder", "8d0fcd40-8b69-44d7-b6c6-f43be84bb308");
user_pref("calendar.registry.8d0fcd40-8b69-44d7-b6c6-f43be84bb308.calendar-main-in-composite", true);
user_pref("calendar.registry.8d0fcd40-8b69-44d7-b6c6-f43be84bb308.disabled", true);
user_pref("calendar.registry.8d0fcd40-8b69-44d7-b6c6-f43be84bb308.name", "Home");
user_pref("calendar.registry.8d0fcd40-8b69-44d7-b6c6-f43be84bb308.type", "storage");
user_pref("calendar.registry.8d0fcd40-8b69-44d7-b6c6-f43be84bb308.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1635850147407");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1635850407);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.13.0");
user_pref("extensions.lastPlatformVersion", "78.13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"6ad2d046-3e37-4a6c-b64f-cc72d13f251c\",\"google@search.mozilla.org\":\"dd6591da-c2db-44a4-880b-a26dbf6c6ddf\",\"amazondotcom@search.mozilla.org\":\"6cb06202-53f1-4acf-a271-3337170db7e2\",\"bing@search.mozilla.org\":\"e0d9b30f-5b91-4a69-bedb-41e1024d93e9\",\"ddg@search.mozilla.org\":\"8db38d8f-7644-4f4b-8d59-0f92cff7eaaa\",\"wikipedia@search.mozilla.org\":\"c1b275cd-83c7-4b52-978b-d82e8d276f9e\"}");
user_pref("idle.lastDailyNotification", 1635850608);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "5967e5d1-711c-4f10-8492-15db19ce4f2");
user_pref("mailnews.filters.migration78", true);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "78.13.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("places.database.lastMaintenance", 1635850608);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("security.sandbox.plugin.tempDirSuffix", "420fc135-978f-4cec-b1f9-f2091123b533");
user_pref("services.blocklist.addons.checked", 1635850291);
user_pref("services.settings.clock_skew_seconds", -5);
user_pref("services.settings.last_etag", "\"1635843467231\"");
user_pref("services.settings.last_update_seconds", 1635850291);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1635850291);
user_pref("services.settings.main.hijack-blocklists.last_check", 1635850291);
user_pref("services.settings.main.language-dictionaries.last_check", 1635850291);
user_pref("services.settings.main.search-config.last_check", 1635850291);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1635850291);
user_pref("services.settings.main.sites-classification.last_check", 1635850291);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1635850291);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1635850608);
user_pref("toolkit.telemetry.cachedClientID", "5999d882-058e-4a91-a055-4fd85905d8ad");
user_pref("toolkit.telemetry.previousBuildID", "20210802223056");
